config/routes.rb
EatgoDashboard::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  #root :to => 'high_voltage/pages#show', :id => 'welcome'
  #root :to => 'category#show', :id => 'home'
  root :to => 'home#index', :id => 'home'
  
  resources 'api', only: [] do
    collection do
      post :list
      get :list
    end
  end

  resources 'category', only: [:show]

  resources 'menu', only: [:index]
  resources 'raw'
end

app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  
  extend OmniauthCallbacks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  layout false

  skip_before_filter :verify_authenticity_token
  def list
    unless params.include? :q
      render :nothing => true and return
    end
    q = params[:q]
    file = File.open(Rails.root.join("files/#{q}.json")).read
    render :json => JSON.parse(file)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def login_required
    if current_user.blank?
      respond_to do |format|
        format.html  {
          authenticate_user!
        }
        format.js{
          render :partial => "common/not_logined"
        }
        format.all {
          head(:unauthorized)
        }
      end
    end
  
  end


  def require_is_admin
    unless (current_user && current_user.admin?)
      redirect_to root_path, :flash => { :error => "no permission" }
    end
  end
  
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  layout 'index'

  def show
    id = params[:id]
    raw_config = File.read("config/config.yml")
    config = YAML.load(raw_config)
    data = File.read(config[Rails.env]['data'])
    @menu = JSON.parse(data)
    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  before_action :load_config

  def index
  end

  private

  def load_config
    raw_config = File.read("config/config.yml")
    config = YAML.load(raw_config)
    data = File.read(config[Rails.env]['data'])
    @menu = JSON.parse(data)
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  layout 'menu'

  def index
    raw_config = File.read("config/config.yml")
    config = YAML.load(raw_config)
    data = File.read(config[Rails.env]['data'])
    @menu = JSON.parse(data)
  end

end

app/controllers/raw_controller.rb
class RawController < ApplicationController
  layout 'raw'
  before_action :load_config

  def index
  end

  def show
    id = params[:id]
    redirect_to raw_index_path if id.nil? or id.empty?

    filename = "files/#{id}.json"
    redirect_to raw_path unless File.exists? filename
    raw_file = File.read(filename)

    @id = id
    map = @map[id] if @map.include? id
    @name = map['name'] unless map.nil?
    @parent = map['parent'] unless map.nil?
    begin
      @content = JSON.pretty_generate(JSON.parse(raw_file))
    rescue
      @content = ""
    end
  end

  def edit
    id = params[:id]
    redirect_to raw_index_path if id.nil? or id.empty?

    filename = "files/#{id}.json"
    redirect_to raw_path unless File.exists? filename
    raw_file = File.read(filename)

    @id = id
    map = @map[id] if @map.include? id
    @name = map['name'] unless map.nil?
    @parent = map['parent'] unless map.nil?
    begin
      @content = JSON.pretty_generate(JSON.parse(raw_file))
    rescue
      @content = ""
    end
  end

  def update
    id = params[:id]
    content = params[:content]
    redirect_to raw_index_path if id.nil? or id.empty?

    filename = "files/#{id}.json"
    file = File.open(filename, 'w')
    file.write(content)
    file.close

    redirect_to raw_path(:id => id), flash: { notice_message: '更新成功' }
  end

  def new
    @parent = @menu.collect {|m| [m['name'], m['id']]}
    @parent.unshift(['<無>', nil])
  end

  def create
    id = params[:id]
    name = params[:name]
    parent_id = params[:parent]
    content = params[:content]
    redirect_to raw_index_path if id.nil? or id.empty?
    redirect_to raw_index_path if name.nil? or name.empty?

    if parent_id.empty?
      @menu.push({"id"=>id, "name"=>name})
    else
      @menu.each do |m|
        if m['id'] == parent_id.to_s
          m['items'] = [] unless m.include? 'items'
          m['items'].push({"id"=>id, "name"=>name})
        end
      end
    end
    save_config()

    filename = "files/#{id}.json"
    file = File.open(filename, 'w')
    file.write(content)
    file.close

    redirect_to raw_path(:id => id), flash: { notice_message: '新增成功' }
  end

  def destroy
    id = params[:id]
    redirect_to raw_index_path if id.nil? or id.empty?

    @menu.each do |m|
      next unless m.include? 'items'
      if m['id'] == id
        m['items'].each { |i| File.delete("files/#{i['id']}.json") if File.exists? "files/#{i['id']}.json" }
      else
        m['items'].delete_if {|i| i["id"] == id}
      end
    end

    @menu.delete_if { |m| m["id"] == id }
    save_config()
    File.delete("files/#{id}.json") if File.exists? "files/#{id}.json"

    redirect_to raw_index_path(), flash: { notice_message: "#{@map[id]} 已刪除" }
  end

  private

  def load_config
    raw_config = File.read("config/config.yml")
    config = YAML.load(raw_config)
    data = File.read(config[Rails.env]['data'])
    @menu = JSON.parse(data)
    @map = {}
    @menu.each do |m|
      @map[m['id']] = {'name' => m['name'], 'parent' => ''}
      if m.include? 'items'
        m['items'].each do |i|
          @map[i['id']] = {'name' => i['name'], 'parent' => m['name']}
        end
      end
    end
  end

  def save_config
    content = JSON.pretty_generate(@menu)
    raw_config = File.read("config/config.yml")
    config = YAML.load(raw_config)
    file = File.open(config[Rails.env]['data'], 'w')
    file.write(content)
    file.close
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/category/show.html.erb
<div class="list-left">
</div>
<div class="list-right">
    <!-- <iframe class="iframe-container"></iframe> -->
</div>

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<footer class="footer">
  <%= render_list :class => "nav nav-pills pull-right" do |li|
      #li << link_to( "Link1", "#")
      #li << link_to( "Link2", "#")   
      #li << link_to( "Link3", "#")
      #li << link_to( "Link4", "#")
  end %>
  <p class="copyright">Copyright @2012 <%= Setting.app_name %> All rights reserved.</p>

</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_menu.html.erb
<div class="navbar navbar-fixed-top ">
      <div class="navbar-inner top ">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to(Setting.app_name, Setting.domain , :class => "brand" )%>

          <!-- <%= render :partial => "common/search_form" %> -->
     
          <div class="nav-collapse">

              <ul class="nav">
                  <% @menu.each do |m| %>
                      <% if m.include? 'items' and m['items'].size > 0 %>
                          <li>
                          <%= link_to "##{m['id']}", :class => 'category' do %>
                              <%= m['name'] %>
                              <%= content_tag(:i,"",class:"icon-caret-down") %>
                          <% end %>
                          <ul class="dropdown-menu dropdown-fix">
                          <% m['items'].each do |i| %>
                          <li class="dropdown">
                          <%= link_to "##{i['id']}" do %>
                              <%= i['name'] %>
                          <% end %>
                          </li>
                          <% end %>
                        </ul>
                          </li>
                      <% else %>
                          <li>
                          <%= link_to "##{m['id']}", :class => 'category' do %>
                              <%= m['name'] %>
                          <% end %>
                          </li>
                      <% end %>
                  <% end %>
              </ul>
              <%#= render_list :class => "nav" do |li|
                  @menu.each do |m|
                      nil.aa
                      li << link_to(m['name'], "##{m['id']}", :class => 'category')
                  end
              end %>

              <%= render :partial => "common/user_nav"%>

          </div>
    </div>
  </div>

  <%= yield :submenu %>

</div>

app/views/common/_not_logined.js.erb
if (confirm("Please login first, proceed?") )
{
	window.location = "/users/sign_in";
}

app/views/common/_search_form.html.erb
 <%= form_tag "/search", :class => "navbar-search", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
      
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">

    <!-- <li>
      <div class="social"> <%=  fb_like(Setting.domain) %>  </div>
      </li> -->

  <% if current_user %>    

    <li class="dropdown">
      <%= link_to "/account" , :class => "dropdown-toggle", :data => { :toggle => "dropdown" } do %>
        <%= current_user.email %>
      <% end %>

      <%= render_list :class => "dropdown-menu" do |li|
          li << link_to("Logout",destroy_user_session_path, :method => :delete )
      end %>

    </li>

<% else %>
    <!-- <li> <%= link_to( "Sign Up" ,new_user_registration_path) %> </li> -->
    <!-- <li> <%= link_to( "Login", new_user_session_path )  %> </li> -->
    <!-- <li> <%= link_to( "FB Login", "/users/auth/facebook" )  %> </li> -->
<% end %>

<li> <%= link_to( "編輯", raw_index_path) %> </li>

</ul>

app/views/home/_list.html.erb
<ul>
    <!--
    <li><a class="list-item" href="#" data-url="https://docs.google.com/a/eatgo.com/spreadsheet/ccc?key=0AlpHifSaI1fpdHlaVzdUZDFCRFk4Ukw0cHdYWThEMlE&usp=drive_web">Eatgovillas Sites</a></li>
    <li><a class="list-item" href="#" data-url="https://docs.google.com/a/eatgo.com/document/d/1HtEZsv65ayLNkNr1sOA5DMH4cvmwMLZnqK_lQU9xPH8">ASA 回家計畫</a></li>
    <li><a class="list-item" href="#" data-url="https://docs.google.com/a/eatgo.com/spreadsheet/ccc?key=0AlpHifSaI1fpdC1vamR1NzlzLWx6a3hzREItX0NibkE&usp=drive_web">eatgo 服務</a></li>
    <li><a class="list-item" href="#" data-url="https://beer.hackpad.com">Beer Hackpad</a></li>
    -->
</ul>

app/views/home/index.html.erb
<div class="list-left">
    <%= render :partial => "home/list" %>
</div>
<div class="list-right">
    <iframe class="iframe-container"></iframe>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  
  <%= yield :stylesheets %>

  <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image:url"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>

</head>

<%= render_body_tag %>

<%= render :partial => "common/menu" %>

  <div class="container">

      <%= notice_message %>

      <div class="content">
        <div class="row">
          <%= yield %>
          <%= yield (:sidebar) %>
        </div> 
    
      </div>

      <!-- <%= render :partial => "common/footer" %> -->
  </div>



  

  <%= render :partial => "common/bootstrap_modal" %>    
  <%= render :partial => "common/facebook_js" %>
  <%= render :partial => "common/google_analytics" %>
 
  <%= javascript_include_tag "application" %>
  <!-- <%= javascript_include_tag "_index" %> -->

  <%= yield :javascripts %>


</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "home" %>
  
  <%= yield :stylesheets %>

  <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image:url"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>

</head>

<%= render_body_tag %>

<%= render :partial => "common/menu" %>

  <div class="container">

      <%= notice_message %>

      <div class="content">
        <div class="row">
          <%= yield %>
          <%= yield (:sidebar) %>
        </div> 
    
      </div>

      <!-- <%= render :partial => "common/footer" %> -->
  </div>



  

  <%= render :partial => "common/bootstrap_modal" %>    
  <%= render :partial => "common/facebook_js" %>
  <%= render :partial => "common/google_analytics" %>
 
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "home" %>

  <%= yield :javascripts %>


</body>
</html>

app/views/layouts/menu.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "_menu" %>
  
  <%= yield :stylesheets %>

  <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image:url"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>

</head>

<%= render_body_tag %>

  <div class="container">

      <%= notice_message %>

      <div class="content">
        <div class="row">
          <%= yield %>
          <%= yield (:sidebar) %>
        </div> 
    
      </div>

      <!-- <%= render :partial => "common/footer" %> -->
  </div>

  <%= render :partial => "common/bootstrap_modal" %>    
  <%= render :partial => "common/facebook_js" %>
  <%= render :partial => "common/google_analytics" %>
 
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "_menu" %>

  <%= yield :javascripts %>

</body>
</html>

app/views/layouts/raw.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "raw" %>
  
  <%= yield :stylesheets %>

  <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image:url"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>

</head>

<%= render_body_tag %>

  <div class="container">

      <%= notice_message %>

      <div class="content">
          <%= yield %>
          <%= yield (:sidebar) %>
      </div>

      <!-- <%= render :partial => "common/footer" %> -->
  </div>

  <%= render :partial => "common/bootstrap_modal" %>    
  <%= render :partial => "common/facebook_js" %>
  <%= render :partial => "common/google_analytics" %>
 
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "raw" %>

  <%= yield :javascripts %>

</body>
</html>

app/views/menu/index.html.erb
<%= render_list :id => 'sortable', :class => 'nav' do |li|
    @menu.each do |m|
        li << content_tag(:a, content_tag(:i) + content_tag(:span, m['name'], :id => m['id']), href: '#')
    end
end %>

app/views/pages/welcome.html.erb
<div class="span12">
	<h1> Welcome </h1>
</div>

app/views/raw/edit.html.erb
<%= form_tag raw_path, method: 'put' do %>
    <h4><%= link_to "返回選單列表", raw_index_path %></h4>
    <%= label_tag :parent, @parent, class: 'parent' %>
    <%= label_tag :name, @name, class: 'name' %>
    <%= label_tag :id, @id, class: 'id' %>
    <br>
    <%= submit_tag "Save", class: 'submit' %>
    <%= button_tag "Cancel", onclick: "javascript:location.href='/raw/#{@id}';return false;" %>
    <%= text_area_tag :content, @content, class: 'content' %>
<% end %>

app/views/raw/index.html.erb
<h3>選單列表</h3>
<h4><%= link_to '返回首頁', root_path %></h4>
<ul>
    <% @menu.each do |m| %>

        <li>
        <% path = raw_path(:id => m['id'])%>
        <%= link_to(content_tag(:i) + content_tag(:span, m['name'], :id=>m['id']), path) %>
        <%= link_to(content_tag(:i, "", class:'icon-remove'), path, method:'delete', class: "remove", data: { confirm: "確定要刪除 \"#{m['name']}\" 嗎？" }) %>
        <% if m.include? 'items' %>
            <ul>
                <% m['items'].each do |i| %>
                    <li>
                    <% sub_path = raw_path(:id => i['id']) %>
                    <%= link_to(content_tag(:i) + content_tag(:span, i['name'], :id=>i['id']), sub_path) %>
                    <%= link_to(content_tag(:i, "", class:'icon-remove'), sub_path, method:'delete', class: "remove", data: { confirm: "確定要刪除 \"#{i['name']}\" 嗎？" }) %>
                    </li>
                <% end %>
            </ul>
        <% end %>
        </li>
    <% end %>
</ul>
<%#= render_list :id => 'sortable' do |li|
    @menu.each do |m|
        li << content_tag(
            :a,
            content_tag(:i) + content_tag(:span, m['name'], :id => m['id']),
            href: raw_path(:id=>m['id'])
        ) + link_to(content_tag(:i, "", class:'icon-remove'), raw_path(:id =>m['id']), method:'delete', class: "remove", data: { confirm: "確定要刪除嗎？" })
    end
end %>
<%= form_tag new_raw_path, method: 'get' do %>
    <%= submit_tag "New" %>
<% end %>

app/views/raw/new.html.erb
<%= form_tag raw_index_path, method: 'post' do %>
    <h4><%= link_to "返回選單列表", raw_index_path %></h4>
    <%= select_tag :parent, options_for_select(@parent), class: 'parent' %>
    <%= text_field_tag :name, @name, class: 'name', placeholder: '顯示名稱' %>
    <%= text_field_tag :id, @id, class: 'id', placeholder: 'ID (英文)' %>
    <br>
    <%= submit_tag "Save", class: 'submit' %>
    <%= button_tag "Cancel", onclick: "javascript:location.href='/raw/#{@id}';return false;" %>
    <%= text_area_tag :content, @content, class: 'content', placeholder: 'JSON 內容' %>
<% end %>

app/views/raw/show.html.erb
<%= form_tag edit_raw_path, method: 'get' do %>
    <h4><%= link_to "返回選單列表", raw_index_path %></h4>
    <%= label_tag :parent, @parent, class: 'parent' %>
    <%= label_tag :name, @name, class: 'name' %>
    <%= label_tag :id, @id, class: 'id' %>
    <br>
    <%= submit_tag "Edit", class: 'submit' %>
    <pre><%= @content %></pre>
<% end %>